import { GENDER_OPTIONS } from './gender';

export const commonLabels = {
  age: 'Age',
  gender: 'Gender',
  languages: 'Languages',
  location: 'Location',
  message: 'Message',
  messages: 'Messages',
  passions: 'Passions',
  search: 'Search',
} as const;

export const profileCopy = {
  aboutThisUser: 'About this user',
  joinedPrefix: 'Joined',
  verifiedBadge: 'Verified',
  verifiedUserTitle: 'Verified user',
  yearsOld: (age: number) => `${age} years old`,
} as const;

export const dashboardCopy = {
  discoverTitle: 'Discover',
  discoverSubtitle: 'Find new connections',
  messagesSubtitle: 'View your conversations',
  noConversationsTitle: 'No conversations yet.',
  profileSubtitle: 'Update your details',
  recentConversationsTitle: 'Recent Conversations',
  sharedPassions: (count?: number) => `${count ?? 0} shared passions`,
  startExploring: 'Start exploring',
  suggestedForYouTitle: 'Suggested for You',
  suggestionsEmpty: 'Complete your profile to get suggestions!',
  welcomeBackPrefix: 'Welcome back,',
  yourProfileTitle: 'Your Profile',
} as const;

export const searchCopy = {
  activeFilters: 'Active Filters',
  ageFilterPrefix: 'Age',
  any: 'Any',
  cancel: 'Cancel',
  clearAll: 'Clear all',
  clearAllFilters: 'Clear all filters',
  deleteSearchTitle: 'Delete Search',
  discoverPeopleSubtitle: 'Find others who share your passions.',
  discoverPeopleTitle: 'Discover People',
  failedToSaveSearch: 'Failed to save search',
  failedToSearchProfiles: 'Failed to search profiles. Please try again.',
  filtersTitle: 'Filters',
  giveSearchNamePlaceholder: 'Give this search a name...',
  keywordsLabel: 'Keywords',
  keywordsPlaceholder: 'Name, bio, etc.',
  languageLabel: 'Language',
  languagePlaceholder: 'English, Spanish...',
  loadMore: 'Load More',
  loading: 'Loading...',
  locationPlaceholder: 'City, Country',
  maxAgeLabel: 'Max Age',
  minAgeLabel: 'Min Age',
  noProfilesFoundDescription: 'Try adjusting your filters or search for something else.',
  noProfilesFoundTitle: 'No profiles found matching your criteria.',
  onlineTitle: 'Online',
  privateProfile: 'Private Profile',
  queryFilterPrefix: 'Search',
  results: (count: number) => `${count} ${count === 1 ? 'result' : 'results'}`,
  save: 'Save',
  saveSearchButton: 'Save Search',
  saveSearchNameLabel: 'Search name',
  savedSearchesTitle: 'Saved Searches',
  saveSearchTitle: 'Save Search',
  searching: 'Searching...',
  selectPassionsPlaceholder: 'Select passions...',
  sortOptions: {
    passions: 'Most Shared Passions',
    recent: 'Most Recent',
  },
  sortResultsLabel: 'Sort results',
  tryAgain: 'Try Again',
  unexpectedError: 'An unexpected error occurred. Please try again.',
} as const;

export const errorPageCopy = {
  subtitle: 'We apologize for the inconvenience.',
  title: 'Something went wrong!',
  tryAgain: 'Try again',
} as const;

export const messagesCopy = {
  blockConfirm: 'Are you sure you want to block this user? They will not be able to message you.',
  blockFailed: 'Failed to block user',
  blockUserTitle: 'Block User',
  checkingLatestChats: 'Checking your latest chats.',
  emptyPrompt: 'Select a conversation to start chatting',
  emptyStateSubtitle: 'Start connecting with people who share your passions!',
  emptyStateTitle: 'No conversations yet',
  findPeople: 'Find People',
  loadingConversations: 'Loading conversations...',
  reportUserTitle: 'Report User',
  sendFailed: 'Failed to send message',
  typeMessageAriaLabel: 'Type a message',
  typeMessagePlaceholder: 'Type a message...',
  userBlocked: 'User blocked',
  youBlockedThisUser: 'You have blocked this user. You cannot send messages.',
  youCannotMessageThisUser: 'You cannot send messages to this user.',
} as const;

export const favoritesCopy = {
  emptyState: "You haven't saved any profiles yet.",
  findPeople: 'Find People',
  loadError: 'Failed to load favorites',
  privateProfile: 'Private Profile',
  removeConfirm: 'Remove from favorites?',
  removeError: 'Failed to remove',
  removeSuccess: 'Removed from favorites',
  removeTitle: 'Remove from Favorites',
  title: 'Favorite Profiles',
} as const;

export const settingsCopy = {
  main: {
    account: 'Account',
    backToDashboard: 'Back to Dashboard',
    changePassword: 'Change Password',
    deleteAccount: 'Delete Account',
    downloadMyData: 'Download my data',
    editProfileDetails: 'Edit Profile Details',
    manageBlockedUsers: 'Manage blocked users',
    notifications: 'Notifications',
    profile: 'Profile',
    profileDescription: 'This is your public presence on Skillogue. Keep it up-to-date so others can connect with you.',
    profileVisibilityPrivacy: 'Profile Visibility & Privacy',
    privacy: 'Privacy',
    requestVerification: 'Request Verification',
    subtitle: 'Manage your account, privacy, and notification preferences.',
    title: 'Settings',
    viewMyProfile: 'View My Profile',
  },
  blocked: {
    backToSettings: 'Back to Settings',
    emptyDescription: "You haven't blocked anyone yet.",
    emptyTitle: 'No Blocked Users',
    loadError: 'Failed to load blocked users',
    subtitle: 'Users you have blocked will not be able to see your profile or send you messages.',
    title: 'Blocked Users',
    unblock: 'Unblock',
    unblockConfirm: (userName: string) => `Are you sure you want to unblock ${userName}?`,
    unblockFallbackError: 'Failed to unblock user',
    unblockSuccess: (userName: string) => `${userName} has been unblocked`,
  },
  privacy: {
    backToSettings: 'Back to Settings',
    loading: 'Loading settings...',
    privateProfileDescription: 'When enabled, only your name and avatar will be visible to others. Your detailed profile info will be hidden.',
    privateProfileTitle: 'Private Profile',
    showAgeDescription: 'Display your age on your public profile.',
    showAgeTitle: 'Show Age',
    showLocationDescription: 'Display your city and country on your public profile.',
    showLocationTitle: 'Show Location',
    subtitle: 'Control who can see your profile and personal details.',
    title: 'Privacy Settings',
    updateError: 'Failed to update setting',
    updateSuccess: 'Settings updated',
  },
  verification: {
    approvedDescription: 'Your profile now displays the verified badge.',
    approvedTitle: 'You are Verified!',
    backToSettings: 'Back to Settings',
    intro: 'Get a verified badge on your profile to build trust with other users. Verified users are more likely to get responses and make connections.',
    loading: 'Loading...',
    notAuthenticated: 'Not authenticated',
    pendingDescription: 'Your request is being reviewed by our team. This usually takes 24-48 hours.',
    pendingTitle: 'Verification Pending',
    rejectedDescription: "Unfortunately, we couldn't verify your profile at this time. You can try again later.",
    rejectedTitle: 'Verification Rejected',
    requestButton: 'Request Verification',
    requestSubmitted: 'Verification request submitted!',
    submitError: 'Failed to submit request',
    title: 'Profile Verification',
    tryAgain: 'Try Again',
  },
  dataExport: {
    backToSettings: 'Back to Settings',
    downloadButton: 'Download My Data',
    exportError: 'Failed to export data',
    exportStarted: 'Data export started',
    includedAccountInfo: 'Account information (Email, ID)',
    includedBlockedUsers: 'Blocked users list',
    includedMessages: 'Message history (Sent and Received)',
    includedPassionsLanguages: 'Your Passions and Languages',
    includedProfileDetails: 'Profile details (Name, Bio, Location)',
    includedTitle: "What's included:",
    intro: 'You have the right to access your personal data. Click the button below to download a copy of your data in JSON format. This includes your profile information, messages, and settings.',
    preparing: 'Preparing Download...',
    title: 'Export Your Data',
  },
  deleteAccount: {
    confirmError: 'To confirm, you must type "DELETE" in the box.',
    confirmLabel: 'To confirm, please type "DELETE" below:',
    confirmPlaceholder: 'DELETE',
    deleteFailed: 'Failed to delete account',
    intro: 'This is a permanent action and cannot be undone. All your data, including your profile, messages, and connections, will be permanently removed.',
    submit: 'Permanently Delete Account',
    title: 'Delete Account',
    unexpectedError: 'An unexpected error occurred. Please try again later.',
  },
  pushNotifications: {
    disable: 'Disable',
    disabledDescription: 'Enable notifications for new messages.',
    enable: 'Enable',
    enabledDescription: 'You are receiving notifications.',
    loadingAriaLabel: 'Loading',
    notSupported: 'Push notifications are not supported in this browser.',
    title: 'Push Notifications',
  },
} as const;

export const reportModalCopy = {
  cancel: 'Cancel',
  error: 'Failed to submit report',
  label: 'Reason for reporting',
  placeholder: 'Please describe why you want to report this user...',
  submit: 'Submit Report',
  submitting: 'Submitting...',
  success: 'Report submitted successfully',
  title: 'Report User',
} as const;

export const onboardingCopy = {
  aboutMe: 'About Me',
  aboutPlaceholder: 'I love hiking and coding...',
  back: 'Back',
  basicInfoStep: 'Basic Info',
  birthDate: 'Birth Date',
  city: 'City',
  completeProfile: 'Complete Profile',
  country: 'Country',
  firstName: 'First Name',
  firstNamePlaceholder: 'Jane',
  gender: 'Gender',
  genderOptions: GENDER_OPTIONS,
  interestsLanguagesStepTitle: 'Step 3: Interests & Languages',
  languages: 'Languages',
  languagesPlaceholder: 'Select languages you speak...',
  lastName: 'Last Name',
  lastNamePlaceholder: 'Doe',
  loading: 'Loading...',
  locationStep: 'Location',
  locationStepTitle: 'Step 2: Location',
  next: 'Next',
  passionsPlaceholder: 'Select your passions...',
  passionsStep: 'Passions',
  passionsWithMinimum: 'Passions (Select at least 3)',
  progressComplete: (step: number, total: number) => `${Math.round((step / total) * 100)}% complete`,
  regionState: 'Region/State',
  selectCity: 'Select City',
  selectCountry: 'Select Country',
  selectGender: 'Select Gender',
  selectRegion: 'Select Region',
  stepCounter: (step: number, total: number) => `Step ${step} of ${total}`,
  stepOneTitle: 'Step 1: The Basics',
  subtitle: "Let's set up your profile to find your tribe.",
  title: 'Welcome to Skillogue!',
  validation: {
    invalidBirthDate: 'Please enter a valid birth date for someone between 18 and 120 years old.',
    maxPassions: 'Please select no more than 10 passions.',
    minPassions: 'Please select at least 3 passions to help us find your tribe.',
    missingBasics: 'Please fill in all required fields.',
    missingLocation: 'Please select your location.',
    saveFailed: 'Failed to save profile',
    shortNames: 'Names must be at least 2 characters long.',
  },
} as const;

export const profilePageCopy = {
  edit: {
    aboutMe: onboardingCopy.aboutMe,
    aboutPlaceholder: 'Tell us about yourself...',
    birthDate: onboardingCopy.birthDate,
    city: onboardingCopy.city,
    country: 'Country',
    editProfile: 'Edit Profile',
    failedToLoad: 'Failed to load profile.',
    failedToUpdate: 'Failed to update profile',
    firstName: onboardingCopy.firstName,
    gender: onboardingCopy.gender,
    interestsAndLanguages: 'Interests & Languages',
    invalidBirthDate: onboardingCopy.validation.invalidBirthDate,
    invalidGender: 'Please select a valid gender.',
    languages: commonLabels.languages,
    languagesPlaceholder: onboardingCopy.languagesPlaceholder,
    lastName: onboardingCopy.lastName,
    loading: 'Loading...',
    location: onboardingCopy.locationStep,
    passions: commonLabels.passions,
    passionsPlaceholder: onboardingCopy.passionsPlaceholder,
    regionState: onboardingCopy.regionState,
    saveChanges: 'Save Changes',
    selectCity: onboardingCopy.selectCity,
    selectCountry: onboardingCopy.selectCountry,
    selectGender: onboardingCopy.selectGender,
    selectRegion: onboardingCopy.selectRegion,
  },
  owner: {
    couldNotLoadProfile: 'Could not load profile.',
    editProfile: 'Edit Profile',
  },
  user: {
    addToFavorites: 'Add to Favorites',
    blockConfirm: (name: string) => `Are you sure you want to block ${name}? You won't see them in search or messages.`,
    blockedSuccess: 'User blocked successfully',
    blockError: 'Error blocking user',
    blockUser: 'Block User',
    cannotViewProfile: 'You cannot view this profile.',
    couldNotFindUser: 'Could not find this user.',
    message: 'Message',
    mustBeLoggedIn: 'You must be logged in to view profiles.',
    noUserId: 'No user ID provided.',
    privateDescription: (name: string) => `${name} has limited who can see their profile details.`,
    privateTitle: 'This profile is private',
    profileNotFound: 'Profile not found',
    profileUnavailable: 'Profile Unavailable',
    removedFromFavorites: 'Removed from favorites',
    removeFavoriteError: 'Failed to remove favorite',
    removeFromFavorites: 'Remove from Favorites',
    reportUser: 'Report User',
    returnToDashboard: 'Return to Dashboard',
    savedToFavorites: 'Saved to favorites',
    saveFavoriteError: 'Failed to save favorite',
    unblock: 'Unblock',
    unblockConfirm: (name: string) => `Unblock ${name}?`,
    unblockError: 'Error unblocking user',
    unblockSuccess: 'User unblocked',
    unblockUser: 'Unblock User',
  },
} as const;

export const marketingPageCopy = {
  home: {
    badge: 'Find your tribe today',
    coreFeaturesTitle: 'Core features',
    ctaHeading: 'Ready to Find Your Tribe?',
    ctaLogIn: 'Log In',
    ctaPrimary: 'Start Searching by Passion',
    ctaSubtitle: 'Join Skillogue today and start connecting with people who truly get you.',
    exploreConnections: 'Explore Connections',
    getStarted: 'Get Started',
    heroHeading: 'Connect by Passion',
    heroSubtitle: 'Skillogue brings together people who share your interests — not just your looks.',
    howItWorksTitle: 'How It Works',
    stats: {
      activeUsers: 'Active Users',
      connections: 'Connections',
      languages: commonLabels.languages,
      passions: commonLabels.passions,
    },
    steps: [
      {
        title: '1. Create Your Profile',
        description: 'Share your passions, interests, and what makes you unique.',
      },
      {
        title: '2. Discover Matches',
        description: 'Find people who share your passions and values.',
      },
      {
        title: '3. Connect & Chat',
        description: 'Start meaningful conversations with your new connections.',
      },
    ] as const,
    featureCards: [
      {
        title: 'Passion-Based Matching',
        description: 'Discover people who love what you love — from coding to cooking, music to mountaineering.',
      },
      {
        title: 'Private Messaging',
        description: 'Chat securely with like-minded individuals in real time.',
      },
      {
        title: 'Safe & Trusted',
        description: 'Built-in safety tools and verified profiles keep your experience secure.',
      },
    ] as const,
  },
  notFound: {
    description: 'Oops! The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.',
    pageNotFound: 'Page Not Found',
    returnHome: 'Return Home',
    searchUsers: 'Search Users',
  },
} as const;

export const componentCopy = {
  avatar: {
    defaultAlt: 'User Avatar',
    loadingAriaLabel: 'Loading avatar',
  },
  button: {
    loading: 'Loading...',
  },
  cookieBanner: {
    accept: 'Accept',
    closeAriaLabel: 'Close',
    textAfterLink: '.',
    textBeforeLink: 'We use cookies to enhance your experience. By continuing to visit this site you agree to our use of cookies. For more information, please see our',
    privacyPolicyLink: 'Privacy Policy',
  },
  modal: {
    closeAriaLabel: 'Close modal',
  },
  multiSelect: {
    defaultPlaceholder: 'Select...',
    noOptionsFound: 'No options found',
    removeSelectedItem: (item: string) => `Remove ${item}`,
    selectedCount: (count: number) => `${count} selected`,
  },
  navbar: {
    closeNavigationMenu: 'Close navigation menu',
    favorites: 'Favorites',
    logIn: 'Log In',
    messages: 'Messages',
    notifications: 'Notifications',
    openNavigationMenu: 'Open navigation menu',
    profile: 'Profile',
    search: 'Search',
    settings: 'Settings',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
  },
  notificationCenter: {
    ago: 'ago',
    ariaLabel: 'Notifications',
    defaultNotification: 'You have a new notification.',
    emptyState: 'No new notifications.',
    emptyStatePageTitle: 'No notifications yet',
    emptyStateSubtitle: "We'll let you know when something important happens.",
    fallbackActorName: 'Someone',
    genericActorName: 'A user',
    markAllAsRead: 'Mark all as read',
    missingActor: 'This notification is from a user who no longer exists.',
    newNotificationFrom: (actorName: string) => `You have a new notification from ${actorName}.`,
    sentMessage: 'sent you a message.',
    title: 'Notifications',
    unreadTitle: 'Unread',
    viewAll: 'View all notifications',
  },
  passwordStrength: {
    minLength: 'At least 8 characters',
    number: 'At least one number',
    symbol: 'At least one symbol',
    uppercase: 'At least one uppercase letter',
  },
  profileCompletion: {
    addBio: 'Add a bio to tell people about yourself.',
    addLanguages: 'Add the languages you speak.',
    addPassions: 'Add more passions to find better connections.',
    title: 'Complete Your Profile',
  },
  footer: {
    allRightsReserved: (year: number) => `© ${year} Skillogue, Inc. All rights reserved.`,
    contactUs: 'Contact Us',
    cookiePolicy: 'Cookie Policy',
    faq: 'FAQ',
    githubAriaLabel: 'GitHub',
    legal: 'Legal',
    linkedinAriaLabel: 'LinkedIn',
    madeWith: 'Made with',
    passionDrivenPeople: 'for passion-driven people',
    privacyPolicy: 'Privacy Policy',
    support: 'Support',
    tagline: 'Connect through passions, not pictures',
    termsOfService: 'Terms of Service',
    twitterAriaLabel: 'Twitter',
  },
} as const;

export const contactCategoryValues = ['general', 'support', 'bug', 'feedback'] as const;

export const staticPageCopy = {
  common: {
    backToHome: 'Back to Home',
    lastUpdated: (date: string) => `Last updated: ${date}`,
  },
  contact: {
    category: 'Category',
    categoryOptions: [
      { value: 'general', label: 'General Inquiry' },
      { value: 'support', label: 'Support Request' },
      { value: 'bug', label: 'Report a Bug' },
      { value: 'feedback', label: 'Feedback' },
    ] as const,
    email: 'Email',
    emailPlaceholder: 'your@email.com',
    failure: 'Failed to send message. Please try again.',
    message: 'Message',
    messagePlaceholder: 'Tell us more...',
    name: 'Name',
    namePlaceholder: 'Your name',
    sendMessage: 'Send Message',
    subject: 'Subject',
    subjectPlaceholder: 'What is this about?',
    subtitle: "Have a question, suggestion, or just want to say hi? We'd love to hear from you.",
    success: 'Message sent successfully! We will get back to you soon.',
    title: 'Contact Us',
    validation: {
      invalidEmail: 'Invalid email address',
      messageMax: (max: number) => `Message must be at most ${max} characters`,
      messageMin: 'Message must be at least 10 characters',
      nameRequired: 'Name is required',
      subjectMin: 'Subject must be at least 5 characters',
    },
  },
  faq: {
    items: [
      {
        question: 'How does Skillogue match people?',
        answer: 'Skillogue focuses on shared passions, profile details, and preferences instead of uploaded profile photos. Search and discovery are built around what people care about and how they want to connect.',
      },
      {
        question: 'Can I hide parts of my profile?',
        answer: 'Yes. You can control privacy-sensitive details such as age and location, and you can also make your profile private if you want to limit what others can see.',
      },
      {
        question: 'How do favorites and messages work?',
        answer: 'You can save profiles to your favorites for quick access and start one-to-one conversations from search results, favorites, or a user profile.',
      },
      {
        question: 'How do blocking and reporting work?',
        answer: 'If another user behaves inappropriately, you can report them. You can also block users so they no longer appear in your experience or contact you.',
      },
      {
        question: 'Do I need to upload a profile picture?',
        answer: 'No. Skillogue intentionally uses generated avatars to keep discovery centered on interests and personality instead of appearance.',
      },
    ] as const,
    subtitle: 'Quick answers about how Skillogue works, what you can control, and how safety features behave.',
    title: 'Frequently Asked Questions',
  },
  cookies: {
    lastUpdated: 'April 26, 2026',
    sections: [
      {
        title: '1. What This Policy Covers',
        body: 'This Cookie Policy explains how Skillogue uses cookies, local storage, and similar browser technologies when you visit the site or use product features. These technologies help us keep the service working, remember your choices, and understand how the product is being used.',
      },
      {
        title: '2. Essential Product Functionality',
        body: 'Some cookies or local storage entries are necessary for authentication, security, session continuity, and core navigation. Without them, sign-in, protected pages, and other important parts of Skillogue may not work as intended.',
      },
      {
        title: '3. Preferences and Settings',
        body: 'We may store settings such as consent choices, notification preferences, and other in-product options so your experience stays consistent across visits and page refreshes.',
      },
      {
        title: '4. Analytics and Performance',
        body: 'We may use cookies or similar technologies to understand page visits, feature usage, and basic performance or reliability trends. This information helps us improve usability, diagnose issues, and make product decisions based on real usage patterns.',
      },
      {
        title: '5. Third-Party Services',
        body: 'Some parts of Skillogue may rely on third-party infrastructure or services that use their own cookies or storage technologies to support hosting, authentication, analytics, or related operational needs. Those providers process data under their own terms and policies.',
      },
      {
        title: '6. Managing Cookies',
        body: 'You can manage or clear cookies through your browser settings, and some browser tools also let you block certain storage technologies entirely. If you disable essential cookies or browser storage, parts of Skillogue may become unavailable or behave unexpectedly.',
      },
      {
        title: '7. Changes to This Policy',
        body: 'We may update this Cookie Policy as the product, legal requirements, or technical setup changes. When we do, we will revise the date shown above.',
      },
      {
        title: '8. Contact',
        body: 'If you have questions about this Cookie Policy, you can contact us through the support options listed on the',
        link: {
          href: '/contact',
          label: 'Contact Us page',
          suffix: '.',
        },
      },
    ] as const,
    title: 'Cookie Policy',
  },
  privacyPolicy: {
    lastUpdated: 'April 26, 2026',
    sections: [
      {
        title: '1. Overview',
        body: 'This Privacy Policy explains what information Skillogue collects, how we use it, and the choices available to you when you use our website and related services. By using Skillogue, you acknowledge the practices described in this policy.',
      },
      {
        title: '2. Information You Provide',
        body: 'When you create an account, complete your profile, communicate through the product, or contact us, you may provide information such as:',
        labeledBullets: [
          {
            label: 'Account Data',
            text: 'such as your email address, login credentials, and account verification details.',
          },
          {
            label: 'Profile Data',
            text: 'such as your name, birth date, gender, bio, location details, passions, languages, profile visibility settings, and avatar preferences.',
          },
          {
            label: 'Communication Data',
            text: 'such as messages, favorites, notifications, support requests, and other interactions you initiate through the service.',
          },
          {
            label: 'Safety and Support Data',
            text: 'such as reports, moderation-related submissions, and information you send to us when asking for help or reporting a problem.',
          },
        ] as const,
      },
      {
        title: '3. Information We Collect Automatically',
        body: 'When you use Skillogue, we may automatically collect limited technical and usage information needed to operate and improve the service, including:',
        bullets: [
          'Device, browser, and log information such as IP address, browser type, pages visited, and timestamps.',
          'Product usage information such as feature interactions, search activity, and reliability or performance diagnostics.',
          'Cookie and similar local storage data used for authentication, preferences, analytics, and core product functionality.',
        ] as const,
      },
      {
        title: '4. How We Use Information',
        body: 'We use information we collect to operate, secure, and improve Skillogue. Depending on the context, this may include:',
        bullets: [
          'Creating and maintaining your account and profile.',
          'Powering profile discovery, messaging, favorites, and notification features.',
          'Personalizing the product experience and remembering your preferences.',
          'Detecting abuse, enforcing our Terms, reviewing reports, and protecting users.',
          'Providing customer support, troubleshooting, analytics, and service improvements.',
          'Complying with legal obligations and responding to lawful requests.',
        ] as const,
      },
      {
        title: '5. When We Share Information',
        body: 'We may share information only as reasonably necessary to run Skillogue and meet legal or safety obligations. This can include sharing with service providers that host infrastructure or support product operations, with authorities when legally required, or in connection with fraud prevention, enforcement, or business transfers. Information visible on your profile is also shared with other users according to your privacy settings.',
      },
      {
        title: '6. Retention and Security',
        body: 'We retain information for as long as reasonably necessary to provide the service, comply with legal obligations, resolve disputes, and enforce our agreements. We use administrative, technical, and organizational safeguards designed to protect personal information, but no system can be guaranteed completely secure.',
      },
      {
        title: '7. Your Choices and Rights',
        body: 'You can review and update parts of your profile information from within the product. Depending on where you live, you may also have legal rights to request access, correction, deletion, restriction, objection, or portability of certain personal data. You may also close your account subject to applicable legal and operational retention requirements.',
      },
      {
        title: '8. Contact Us',
        body: 'If you have questions about this Privacy Policy or your data, please use our',
        link: {
          href: '/contact',
          label: 'Contact Us page',
          suffix: '.',
        },
      },
    ] as const,
    title: 'Privacy Policy',
  },
  termsOfService: {
    lastUpdated: 'April 26, 2026',
    sections: [
      {
        title: '1. Agreement to Terms',
        body: 'These Terms of Service govern your access to Skillogue, including the website, product features, and related services. By creating an account, browsing the site, or otherwise using Skillogue, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the service.',
      },
      {
        title: '2. Eligibility and Accurate Information',
        body: 'You must be at least 18 years old and legally able to enter into a binding agreement to use Skillogue. You agree to provide accurate account and profile information, keep it reasonably up to date, and create an account only for yourself.',
      },
      {
        title: '3. Your Account and Security',
        body: 'You are responsible for maintaining the confidentiality of your login credentials and for activity that occurs through your account. If you believe your account has been accessed without authorization, you must notify us promptly and take reasonable steps to secure it.',
      },
      {
        title: '4. How You May Use Skillogue',
        body: 'Skillogue is intended to help people discover and connect around shared passions. Subject to these Terms, we grant you a limited, non-exclusive, revocable right to use the service for personal, non-commercial use.',
      },
      {
        title: '5. Your Content and Profile Information',
        body: 'You retain ownership of the information and content you submit to Skillogue. You grant us a limited license to host, store, process, reproduce, and display that content as needed to operate, secure, moderate, and improve the service.',
      },
      {
        title: '6. Safety and Prohibited Conduct',
        body: 'You agree not to engage in any of the following prohibited activities:',
        bullets: [
          'Impersonating another person or misrepresenting your identity, age, or intent.',
          'Harassing, threatening, stalking, defaming, or discriminating against other users.',
          'Posting unlawful, fraudulent, hateful, violent, or sexually explicit content.',
          'Using bots, scraping tools, reverse engineering, or other automation to access or interfere with the service.',
          'Sending spam, unauthorized promotions, or otherwise using the service for illegal or abusive purposes.',
          'Attempting to access accounts, data, or areas of the service that you are not authorized to use.',
        ] as const,
      },
      {
        title: '7. Moderation and Enforcement',
        body: 'We may review reports, investigate suspected violations, remove content, limit visibility, suspend features, or terminate accounts when reasonably necessary to protect users, comply with law, or enforce these Terms. We are not obligated to monitor every interaction on the service.',
      },
      {
        title: '8. No Guarantee of Matches or Availability',
        body: 'Skillogue does not guarantee matches, replies, compatibility, uninterrupted availability, or that every profile or interaction will meet your expectations. Features may change, be limited, or be removed over time.',
      },
      {
        title: '9. Termination and Account Closure',
        body: 'You may stop using Skillogue at any time. We may suspend or terminate your access if we reasonably believe you violated these Terms, created risk for other users, or exposed Skillogue to legal, trust, or security issues.',
      },
      {
        title: '10. Disclaimers and Limitation of Liability',
        body: 'To the fullest extent permitted by law, Skillogue is provided on an "as is" and "as available" basis without warranties of any kind. Skillogue and its operators will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of data, profits, goodwill, or business opportunities arising out of or related to your use of the service.',
      },
      {
        title: '11. Changes to These Terms',
        body: 'We may update these Terms to reflect product, legal, or operational changes. When we make material changes, we will update the date above and may provide additional notice where appropriate. Your continued use of Skillogue after updated Terms take effect means you accept them.',
      },
      {
        title: '12. Contact Us',
        body: 'If you have any questions about these Terms, please use our',
        link: {
          href: '/contact',
          label: 'Contact Us page',
          suffix: '.',
        },
      },
    ] as const,
    title: 'Terms of Service',
  },
} as const;

export const signUpCopy = {
  agreementAlert: 'You must agree to the Terms of Service and Privacy Policy to create an account.',
  agreementPrefix: 'I agree to the',
  agreementSuffix: '.',
  alreadyHaveAccount: 'Already have an account?',
  createAccount: 'Create Your Account',
  creatingAccount: 'Creating Account...',
  emailAddress: 'Email Address',
  emailPlaceholder: 'you@example.com',
  emptyFieldsAlert: 'Please fill in both fields',
  password: 'Password',
  passwordPlaceholder: '••••••••',
  privacyPolicy: 'Privacy Policy',
  signIn: 'Sign in',
  signUp: 'Sign Up',
  strengthAlert: 'Please ensure your password meets all the strength requirements.',
  subtitle: 'Start building real connections today',
  successAlert: '🎉 Check your email for the confirmation link!',
  termsOfService: 'Terms of Service',
} as const;

export const authCopy = {
  forgotPassword: {
    backToLogin: 'Back to Login',
    emailAddress: signUpCopy.emailAddress,
    emailPlaceholder: signUpCopy.emailPlaceholder,
    failure: 'Failed to send reset email',
    loading: 'Sending...',
    submit: 'Send Reset Link',
    submittedPrefix: "We've sent a password reset link to",
    submittedTitle: 'Check Your Email',
    subtitle: 'Enter your email to receive a reset link',
    title: 'Reset Password',
  },
  login: {
    email: 'Email',
    emailPlaceholder: signUpCopy.emailPlaceholder,
    emptyFieldsError: signUpCopy.emptyFieldsAlert,
    forgotPassword: 'Forgot your password?',
    footerPrefix: "Don't have an account?",
    loading: 'Signing in...',
    password: signUpCopy.password,
    passwordPlaceholder: signUpCopy.passwordPlaceholder,
    signIn: 'Sign In',
    signInSubtitle: 'Sign in to your account',
    signUp: 'Sign up',
    title: 'Welcome Back',
    unexpectedError: 'An error occurred',
  },
  resendVerification: {
    backToLogin: 'Back to Login',
    backToSignUp: 'Back to Sign Up',
    defaultMessage: "If you didn't receive the verification email, confirm your password and we'll send another one.",
    email: 'Email',
    emailPasswordRequired: 'Email and password are required to send another verification email.',
    emailPlaceholder: signUpCopy.emailPlaceholder,
    failure: 'Failed to resend verification email.',
    loading: 'Sending...',
    password: signUpCopy.password,
    passwordPlaceholder: signUpCopy.passwordPlaceholder,
    submit: 'Send Another Verification Email',
    success: 'We sent you a new verification email. Please check your inbox.',
    title: 'Need Another Verification Email?',
  },
  resetPassword: {
    confirmPassword: 'Confirm Password',
    emptyFieldsError: 'Please fill in all fields',
    invalidLink: 'Invalid or expired link. Please request a new password reset.',
    loading: 'Updating Password...',
    mismatchError: 'Passwords do not match',
    newPassword: 'New Password',
    passwordPlaceholder: signUpCopy.passwordPlaceholder,
    strengthError: 'Please ensure your new password meets all the strength requirements.',
    submit: 'Update Password',
    submitError: 'Failed to reset password',
    subtitle: 'Please choose a strong password for your account',
    successSubtitle: 'Redirecting to login...',
    successTitle: 'Password Updated!',
    title: 'Set New Password',
  },
  verifyEmail: {
    backToLogin: 'Go to Login',
    backToSignUp: 'Back to Sign Up',
    failure: 'Failed to verify email.',
    invalidLink: 'Invalid or expired verification link.',
    loadingMessage: 'Verifying your email address...',
    successMessage: 'Your email has been verified. You can sign in now.',
    title: 'Email Verification',
  },
} as const;

export const adminCopy = {
  dashboard: {
    subtitle: 'Welcome to the Skillogue Admin Panel. Use the sidebar to navigate.',
    title: 'Admin Dashboard',
  },
  layout: {
    dashboard: 'Dashboard',
    loading: 'Loading...',
    reports: 'Reports',
    users: 'Users',
    verification: 'Verification',
  },
  reports: {
    empty: 'No reports found.',
    loading: 'Loading...',
    reportAgainstPrefix: 'Report against',
    reportedByPrefix: 'Reported by:',
    statusOptions: [
      { value: 'pending', label: 'Pending' },
      { value: 'reviewed', label: 'Reviewed' },
      { value: 'resolved', label: 'Resolved' },
    ] as const,
    title: 'User Reports',
  },
  verification: {
    actions: 'Actions',
    approveTitle: 'Approve',
    date: 'Date',
    empty: 'No pending requests',
    failedToApprove: 'Failed to approve',
    failedToReject: 'Failed to reject',
    loading: 'Loading...',
    rejected: 'Request rejected',
    title: 'Verification Requests',
    user: 'User',
    userVerified: 'User verified successfully',
    rejectTitle: 'Reject',
  },
} as const;