-- Migration: Add missing tables and RPC functions for Skillogue
-- This file adds:
-- 1. blocked_users table
-- 2. push_subscriptions table
-- 3. analytics_events table
-- 4. All required RPC functions

-- =====================================================
-- TABLE: blocked_users
-- =====================================================
CREATE TABLE IF NOT EXISTS blocked_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    blocker_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    blocked_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    UNIQUE(blocker_id, blocked_id)
);

ALTER TABLE blocked_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage own blocked users" ON blocked_users
    FOR ALL USING (auth.uid() = blocker_id);

CREATE POLICY "Allow users to check if blocked" ON blocked_users
    FOR SELECT USING (auth.uid() = blocker_id OR auth.uid() = blocked_id);

-- =====================================================
-- TABLE: push_subscriptions
-- =====================================================
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    p256dh TEXT,
    auth TEXT,
    UNIQUE(user_id, endpoint)
);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage own push subscriptions" ON push_subscriptions
    FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- TABLE: analytics_events
-- =====================================================
CREATE TABLE IF NOT EXISTS analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    event_name TEXT NOT NULL,
    properties JSONB DEFAULT '{}',
    path TEXT
);

ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert analytics" ON analytics_events
    FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);

CREATE POLICY "Allow users to read own analytics" ON analytics_events
    FOR SELECT USING (auth.uid() = user_id OR auth.role() = 'authenticated');

-- =====================================================
-- RPC FUNCTION: get_distinct_countries
-- =====================================================
CREATE OR REPLACE FUNCTION get_distinct_countries()
RETURNS TABLE(country TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY SELECT DISTINCT l.country FROM locations l WHERE l.country IS NOT NULL ORDER BY l.country;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_distinct_regions
-- =====================================================
CREATE OR REPLACE FUNCTION get_distinct_regions(p_country TEXT)
RETURNS TABLE(region TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY SELECT DISTINCT l.region FROM locations l WHERE l.country = p_country AND l.region IS NOT NULL ORDER BY l.region;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_distinct_cities
-- =====================================================
CREATE OR REPLACE FUNCTION get_distinct_cities(p_country TEXT, p_region TEXT DEFAULT NULL)
RETURNS TABLE(city TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF p_region IS NOT NULL THEN
        RETURN QUERY SELECT DISTINCT l.city FROM locations l WHERE l.country = p_country AND l.region = p_region AND l.city IS NOT NULL ORDER BY l.city;
    ELSE
        RETURN QUERY SELECT DISTINCT l.city FROM locations l WHERE l.country = p_country AND l.city IS NOT NULL ORDER BY l.city;
    END IF;
END;
$$;

-- =====================================================
-- TABLE: message_reads (for read receipts)
-- =====================================================
CREATE TABLE IF NOT EXISTS message_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    UNIQUE(user_id, message_id)
);

ALTER TABLE message_reads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to manage own message reads" ON message_reads FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- RPC FUNCTION: get_unread_message_count
-- =====================================================
CREATE OR REPLACE FUNCTION get_unread_message_count(current_user_id UUID)
RETURNS TABLE(count BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY 
    SELECT COUNT(*)::BIGINT
    FROM messages
    WHERE receiver_id = current_user_id
    AND id NOT IN (
        SELECT message_id 
        FROM message_reads 
        WHERE user_id = current_user_id
    );
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_recent_conversations
-- =====================================================
CREATE OR REPLACE FUNCTION get_recent_conversations(current_user_id UUID)
RETURNS TABLE(
    conversation_id TEXT,
    user_id TEXT,
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    last_message TEXT,
    last_message_time TIMESTAMPTZ,
    unread_count BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    WITH conversation AS (
        SELECT 
            CASE WHEN m.sender_id = current_user_id THEN m.receiver_id ELSE m.sender_id END as other_user_id,
            m.content as last_message,
            m.created_at as last_message_time,
            ROW_NUMBER() OVER (
                PARTITION BY CASE WHEN m.sender_id = current_user_id THEN m.receiver_id ELSE m.sender_id END 
                ORDER BY m.created_at DESC
            ) as rn
        FROM messages m
        WHERE m.sender_id = current_user_id OR m.receiver_id = current_user_id
    ),
    unread AS (
        SELECT receiver_id, COUNT(*) as cnt
        FROM messages
        WHERE receiver_id = current_user_id
        AND id NOT IN (SELECT message_id FROM message_reads WHERE user_id = current_user_id)
        GROUP BY receiver_id
    )
    SELECT 
        c.other_user_id::TEXT as conversation_id,
        p.id::TEXT as user_id,
        p.first_name,
        p.last_name,
        p.avatar_url,
        c.last_message,
        c.last_message_time,
        COALESCE(u.cnt, 0)::BIGINT as unread_count
    FROM conversation c
    JOIN profiles p ON p.id = c.other_user_id
    LEFT JOIN unread u ON u.receiver_id = c.other_user_id
    WHERE c.rn = 1
    ORDER BY c.last_message_time DESC;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_suggested_profiles
-- =====================================================
CREATE OR REPLACE FUNCTION get_suggested_profiles(current_user_id UUID, p_limit INT DEFAULT 10)
RETURNS TABLE(
    id TEXT,
    first_name TEXT,
    last_name TEXT,
    about_me TEXT,
    avatar_url TEXT,
    shared_passions_count INT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id::TEXT,
        p.first_name,
        p.last_name,
        p.about_me,
        p.avatar_url,
        COUNT(up.passion_id)::INT as shared_passions_count
    FROM profiles p
    LEFT JOIN user_passions up ON up.user_id = p.id
    LEFT JOIN user_passions my_up ON my_up.user_id = current_user_id AND my_up.passion_id = up.passion_id
    LEFT JOIN blocked_users bu ON (bu.blocker_id = current_user_id AND bu.blocked_id = p.id) OR (bu.blocker_id = p.id AND bu.blocked_id = current_user_id)
    WHERE p.id != current_user_id
    AND bu.id IS NULL
    AND my_up.passion_id IS NOT NULL
    GROUP BY p.id, p.first_name, p.last_name, p.about_me, p.avatar_url
    ORDER BY shared_passions_count DESC, RANDOM()
    LIMIT p_limit;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_profiles_for_passion
-- =====================================================
CREATE OR REPLACE FUNCTION get_profiles_for_passion(p_passion_id BIGINT, p_limit INT DEFAULT 10)
RETURNS TABLE(
    id TEXT,
    first_name TEXT,
    last_name TEXT,
    about_me TEXT,
    avatar_url TEXT,
    city TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id::TEXT,
        p.first_name,
        p.last_name,
        p.about_me,
        p.avatar_url,
        l.city
    FROM profiles p
    JOIN user_passions up ON up.user_id = p.id
    LEFT JOIN locations l ON l.id = p.location_id
    WHERE up.passion_id = p_passion_id
    ORDER BY p.created_at DESC
    LIMIT p_limit;
END;
$$;

-- =====================================================
-- RPC FUNCTION: search_profiles
-- =====================================================
CREATE OR REPLACE FUNCTION search_profiles(
    p_query TEXT DEFAULT NULL,
    p_location TEXT DEFAULT NULL,
    p_min_age INT DEFAULT NULL,
    p_max_age INT DEFAULT NULL,
    p_gender TEXT DEFAULT NULL,
    p_passion_ids BIGINT[] DEFAULT NULL,
    p_language TEXT DEFAULT NULL,
    p_limit INT DEFAULT 20,
    p_offset INT DEFAULT 0
)
RETURNS TABLE(
    id TEXT,
    first_name TEXT,
    last_name TEXT,
    about_me TEXT,
    location TEXT,
    age INT,
    gender TEXT,
    profile_languages TEXT[],
    created_at TIMESTAMPTZ,
    profilepassions TEXT[]
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id::TEXT,
        p.first_name,
        p.last_name,
        p.about_me,
        COALESCE(l.city, '') || ', ' || COALESCE(l.country, ''),
        p.age,
        p.gender,
        ARRAY_AGG(DISTINCT lang.name) FILTER (WHERE lang.name IS NOT NULL),
        p.created_at,
        ARRAY_AGG(DISTINCT passion.name) FILTER (WHERE passion.name IS NOT NULL)
    FROM profiles p
    LEFT JOIN locations l ON l.id = p.location_id
    LEFT JOIN profile_languages pl ON pl.profile_id = p.id
    LEFT JOIN languages lang ON lang.id = pl.language_id
    LEFT JOIN user_passions up ON up.user_id = p.id
    LEFT JOIN passions passion ON passion.id = up.passion_id
    LEFT JOIN blocked_users bu ON (bu.blocker_id = auth.uid() AND bu.blocked_id = p.id) OR (bu.blocker_id = p.id AND bu.blocked_id = auth.uid())
    WHERE bu.id IS NULL
    AND p.id != COALESCE(auth.uid(), p.id)
    AND (p_query IS NULL OR p.first_name ILIKE '%' || p_query || '%' OR p.last_name ILIKE '%' || p_query || '%' OR p.about_me ILIKE '%' || p_query || '%')
    AND (p_location IS NULL OR l.city ILIKE '%' || p_location || '%' OR l.country ILIKE '%' || p_location || '%')
    AND (p_min_age IS NULL OR p.age >= p_min_age)
    AND (p_max_age IS NULL OR p.age <= p_max_age)
    AND (p_gender IS NULL OR p.gender = p_gender)
    AND (p_passion_ids IS NULL OR up.passion_id = ANY(p_passion_ids))
    GROUP BY p.id, p.first_name, p.last_name, p.about_me, l.city, l.country, p.age, p.gender, p.created_at
    ORDER BY p.created_at DESC
    LIMIT p_limit OFFSET p_offset;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_conversations
-- =====================================================
CREATE OR REPLACE FUNCTION get_conversations(current_user_id UUID)
RETURNS TABLE(
    conversation_id TEXT,
    user_id TEXT,
    first_name TEXT,
    last_name TEXT,
    avatar_url TEXT,
    last_message TEXT,
    last_message_time TIMESTAMPTZ,
    unread_count BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY SELECT * FROM get_recent_conversations(current_user_id);
END;
$$;

-- =====================================================
-- RPC FUNCTION: mark_messages_as_read
-- =====================================================
CREATE OR REPLACE FUNCTION mark_messages_as_read(sender_id_param UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    INSERT INTO message_reads (user_id, message_id)
    SELECT current_user, id
    FROM messages
    WHERE sender_id = sender_id_param AND receiver_id = current_user
    ON CONFLICT (user_id, message_id) DO NOTHING;
END;
$$;

-- =====================================================
-- RPC FUNCTION: is_blocked
-- =====================================================
CREATE OR REPLACE FUNCTION is_blocked(target_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
    blocked BOOLEAN;
BEGIN
    current_user := auth.uid();
    IF current_user IS NULL THEN
        RETURN FALSE;
    END IF;
    
    SELECT EXISTS(
        SELECT 1 FROM blocked_users 
        WHERE blocker_id = current_user AND blocked_id = target_id
    ) INTO blocked;
    
    RETURN blocked;
END;
$$;

-- =====================================================
-- RPC FUNCTION: is_blocked_by
-- =====================================================
CREATE OR REPLACE FUNCTION is_blocked_by(target_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
    blocked BOOLEAN;
BEGIN
    current_user := auth.uid();
    IF current_user IS NULL THEN
        RETURN FALSE;
    END IF;
    
    SELECT EXISTS(
        SELECT 1 FROM blocked_users 
        WHERE blocker_id = target_id AND blocked_id = current_user
    ) INTO blocked;
    
    RETURN blocked;
END;
$$;

-- =====================================================
-- RPC FUNCTION: block_user
-- =====================================================
CREATE OR REPLACE FUNCTION block_user(target_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    INSERT INTO blocked_users (blocker_id, blocked_id)
    VALUES (current_user, target_id)
    ON CONFLICT (blocker_id, blocked_id) DO NOTHING;
END;
$$;

-- =====================================================
-- RPC FUNCTION: unblock_user
-- =====================================================
CREATE OR REPLACE FUNCTION unblock_user(target_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    DELETE FROM blocked_users 
    WHERE blocker_id = current_user AND blocked_id = target_id;
END;
$$;

-- =====================================================
-- RPC FUNCTION: is_saved (favorite)
-- =====================================================
CREATE OR REPLACE FUNCTION is_saved(target_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
    saved BOOLEAN;
BEGIN
    current_user := auth.uid();
    IF current_user IS NULL THEN
        RETURN FALSE;
    END IF;
    
    SELECT EXISTS(
        SELECT 1 FROM favorites 
        WHERE user_id = current_user AND favorite_id = target_id
    ) INTO saved;
    
    RETURN saved;
END;
$$;

-- =====================================================
-- RPC FUNCTION: save_profile
-- =====================================================
CREATE OR REPLACE FUNCTION save_profile(target_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    INSERT INTO favorites (user_id, favorite_id)
    VALUES (current_user, target_id)
    ON CONFLICT (user_id, favorite_id) DO NOTHING;
END;
$$;

-- =====================================================
-- RPC FUNCTION: unsave_profile
-- =====================================================
CREATE OR REPLACE FUNCTION unsave_profile(target_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    DELETE FROM favorites 
    WHERE user_id = current_user AND favorite_id = target_id;
END;
$$;

-- =====================================================
-- RPC FUNCTION: get_saved_profiles
-- =====================================================
CREATE OR REPLACE FUNCTION get_saved_profiles()
RETURNS TABLE(
    id TEXT,
    first_name TEXT,
    last_name TEXT,
    about_me TEXT,
    avatar_url TEXT,
    city TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    RETURN QUERY
    SELECT 
        p.id::TEXT,
        p.first_name,
        p.last_name,
        p.about_me,
        p.avatar_url,
        l.city
    FROM favorites f
    JOIN profiles p ON p.id = f.favorite_id
    LEFT JOIN locations l ON l.id = p.location_id
    WHERE f.user_id = current_user;
END;
$$;

-- =====================================================
-- RPC FUNCTION: delete_user_account
-- =====================================================
CREATE OR REPLACE FUNCTION delete_user_account()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    current_user UUID;
BEGIN
    current_user := auth.uid();
    
    DELETE FROM message_reads WHERE user_id = current_user;
    DELETE FROM messages WHERE sender_id = current_user OR receiver_id = current_user;
    DELETE FROM notifications WHERE user_id = current_user OR actor_id = current_user;
    DELETE FROM favorites WHERE user_id = current_user OR favorite_id = current_user;
    DELETE FROM blocked_users WHERE blocker_id = current_user OR blocked_id = current_user;
    DELETE FROM user_passions WHERE user_id = current_user;
    DELETE FROM profile_languages WHERE profile_id = current_user;
    DELETE FROM saved_searches WHERE user_id = current_user;
    DELETE FROM push_subscriptions WHERE user_id = current_user;
    DELETE FROM reports WHERE reporter_id = current_user OR reported_id = current_user;
    DELETE FROM verification_requests WHERE user_id = current_user;
    DELETE FROM profiles WHERE id = current_user;
END;
$$;

-- =====================================================
-- Add indexes for better performance
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_messages_sender_receiver ON messages(sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_user_passions_user ON user_passions(user_id);
CREATE INDEX IF NOT EXISTS idx_blocked_users_blocker ON blocked_users(blocker_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id);
-- Production Setup SQL Script for Skillogue
-- This script should be applied to production database
-- Contains: Blocking Enhancement, Contact Us, Additional RLS Policies

-- =====================================================
-- CONTACT REQUESTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved'))
);

ALTER TABLE contact_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can submit a contact request
CREATE POLICY "Allow anyone to create contact requests" ON contact_requests
    FOR INSERT WITH CHECK (true);

-- Policy: Only authenticated users can see their own requests
CREATE POLICY "Allow users to view own contact requests" ON contact_requests
    FOR SELECT USING (auth.uid() = user_id);

-- Policy: Admins can view all requests
CREATE POLICY "Allow admins to view all contact requests" ON contact_requests
    FOR SELECT USING (auth.role() = 'authenticated');

-- =====================================================
-- ENHANCED BLOCKING FUNCTIONALITY
-- =====================================================
-- Update blocked_users to include blocking from messaging/search

-- Create a function to check mutual blocking
CREATE OR REPLACE FUNCTION check_mutual_block(user_a UUID, user_b UUID)
RETURNS TABLE(blocked_by_a BOOLEAN, blocked_by_b BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        EXISTS(SELECT 1 FROM blocked_users WHERE blocker_id = user_a AND blocked_id = user_b) as blocked_by_a,
        EXISTS(SELECT 1 FROM blocked_users WHERE blocker_id = user_b AND blocked_id = user_a) as blocked_by_b;
END;
$$;

-- =====================================================
-- ENHANCED FAVORITES FUNCTIONALITY
-- =====================================================
-- Add notes to favorites
ALTER TABLE favorites ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE favorites ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- =====================================================
-- ADDITIONAL RLS POLICIES
-- =====================================================

-- Profiles: Hide blocked users from search results
-- (Already handled in search_profiles RPC function)

-- Messages: Prevent blocked users from messaging each other
CREATE OR REPLACE FUNCTION can_send_message(receiver_uuid UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    sender_uuid UUID;
    blocked BOOLEAN;
BEGIN
    sender_uuid := auth.uid();
    IF sender_uuid IS NULL THEN
        RETURN FALSE;
    END IF;
    
    SELECT EXISTS(
        SELECT 1 FROM blocked_users 
        WHERE blocker_id = receiver_uuid AND blocked_id = sender_uuid
    ) INTO blocked;
    
    RETURN NOT blocked;
END;
$$;

-- Update messages insert policy
DROP POLICY IF EXISTS "Allow users to send messages" ON messages;
CREATE POLICY "Allow users to send messages" ON messages
    FOR INSERT WITH CHECK (auth.uid() = sender_id AND can_send_message(receiver_id) = true);

-- =====================================================
-- ADMIN POLICIES
-- =====================================================

-- Reports: Allow admins to view all reports
CREATE POLICY "Allow admins to view all reports" ON reports
    FOR SELECT USING (auth.role() = 'authenticated');

-- Reports: Allow admins to update report status
CREATE POLICY "Allow admins to update reports" ON reports
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Verification requests: Allow admins to view all
CREATE POLICY "Allow admins to view all verification requests" ON verification_requests
    FOR SELECT USING (auth.role() = 'authenticated');

-- Verification requests: Allow admins to update status
CREATE POLICY "Allow admins to update verification requests" ON verification_requests
    FOR UPDATE USING (auth.role() = 'authenticated');

-- =====================================================
-- PERFORMANCE INDEXES
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_profiles_location ON profiles(location_id);
CREATE INDEX IF NOT EXISTS idx_profiles_age_gender ON profiles(age, gender);
CREATE INDEX IF NOT EXISTS idx_profiles_verified ON profiles(verified) WHERE verified = true;
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_verification_status ON verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_contact_status ON contact_requests(status);

-- =====================================================
-- SEED ADDITIONAL LOCATIONS
-- =====================================================
INSERT INTO locations (city, region, country) VALUES
    ('Miami', 'Florida', 'USA'),
    ('Seattle', 'Washington', 'USA'),
    ('Chicago', 'Illinois', 'USA'),
    ('Boston', 'Massachusetts', 'USA'),
    ('Austin', 'Texas', 'USA'),
    ('Denver', 'Colorado', 'USA'),
    ('San Francisco', 'California', 'USA'),
    ('Manchester', 'England', 'UK'),
    ('Edinburgh', 'Scotland', 'UK'),
    ('Birmingham', 'England', 'UK'),
    ('Munich', 'Bavaria', 'Germany'),
    ('Hamburg', 'Hamburg', 'Germany'),
    ('Madrid', 'Madrid', 'Spain'),
    ('Valencia', 'Valencia', 'Spain'),
    ('Milan', 'Lombardy', 'Italy'),
    ('Naples', 'Campania', 'Italy'),
    ('Sydney', 'New South Wales', 'Australia'),
    ('Melbourne', 'Victoria', 'Australia'),
    ('Brisbane', 'Queensland', 'Australia'),
    ('Vancouver', 'British Columbia', 'Canada'),
    ('Montreal', 'Quebec', 'Canada'),
    ('Calgary', 'Alberta', 'Canada'),
    ('Dubai', 'Dubai', 'UAE'),
    ('Abu Dhabi', 'Abu Dhabi', 'UAE'),
    ('Doha', 'Doha', 'Qatar')
ON CONFLICT DO NOTHING;
-- Enhancements SQL Script for Skillogue
-- This script adds Push Notifications and Analytics features
-- Should be applied after production_setup.sql

-- =====================================================
-- PUSH NOTIFICATIONS ENHANCEMENTS
-- =====================================================

-- Add columns to push_subscriptions for better tracking
ALTER TABLE push_subscriptions 
    ADD COLUMN IF NOT EXISTS browser TEXT,
    ADD COLUMN IF NOT EXISTS os TEXT,
    ADD COLUMN IF NOT EXISTS last_used TIMESTAMPTZ DEFAULT NOW();

-- Create function to clean up old push subscriptions
CREATE OR REPLACE FUNCTION cleanup_old_push_subscriptions()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM push_subscriptions 
    WHERE created_at < NOW() - INTERVAL '30 days';
END;
$$;

-- =====================================================
-- ANALYTICS ENHANCEMENTS
-- =====================================================

-- Add columns to analytics_events for better tracking
ALTER TABLE analytics_events
    ADD COLUMN IF NOT EXISTS session_id TEXT,
    ADD COLUMN IF NOT EXISTS device_type TEXT,
    ADD COLUMN IF NOT EXISTS browser TEXT,
    ADD COLUMN IF NOT EXISTS referrer TEXT;

-- Create index for analytics queries
CREATE INDEX IF NOT EXISTS idx_analytics_events_user_date ON analytics_events(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_name ON analytics_events(event_name);

-- =====================================================
-- ANALYTICS AGGREGATED VIEWS (Materialized)
-- =====================================================

-- Daily active users view
CREATE MATERIALIZED VIEW IF NOT EXISTS daily_active_users AS
SELECT 
    DATE(created_at) as date,
    COUNT(DISTINCT user_id) as active_users
FROM analytics_events
WHERE user_id IS NOT NULL
GROUP BY DATE(created_at);

-- Daily event counts view
CREATE MATERIALIZED VIEW IF NOT EXISTS daily_event_counts AS
SELECT 
    DATE(created_at) as date,
    event_name,
    COUNT(*) as event_count
FROM analytics_events
GROUP BY DATE(created_at), event_name;

-- Refresh function for materialized views
CREATE OR REPLACE FUNCTION refresh_analytics_views()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW daily_active_users;
    REFRESH MATERIALIZED VIEW daily_event_counts;
END;
$$;

-- =====================================================
-- USER ENGAGEMENT METRICS
-- =====================================================

-- Function to get user engagement score
CREATE OR REPLACE FUNCTION get_user_engagement_score(user_uuid UUID)
RETURNS TABLE(
    profile_views INT,
    messages_sent INT,
    messages_received INT,
    searchesPerformed INT,
    engagement_score DECIMAL
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    profile_view_count INT;
    msg_sent_count INT;
    msg_received_count INT;
    search_count INT;
BEGIN
    -- Count profile views (from analytics)
    SELECT COUNT(*)::INT INTO profile_view_count
    FROM analytics_events
    WHERE user_id = user_uuid AND event_name = 'profile_view';
    
    -- Count messages sent
    SELECT COUNT(*)::INT INTO msg_sent_count
    FROM messages
    WHERE sender_id = user_uuid;
    
    -- Count messages received
    SELECT COUNT(*)::INT INTO msg_received_count
    FROM messages
    WHERE receiver_id = user_uuid;
    
    -- Count searches
    SELECT COUNT(*)::INT INTO search_count
    FROM analytics_events
    WHERE user_id = user_uuid AND event_name = 'search';
    
    -- Calculate engagement score (0-100)
    RETURN QUERY
    SELECT 
        profile_view_count,
        msg_sent_count,
        msg_received_count,
        search_count,
        LEAST(100, 
            (profile_view_count * 1) + 
            (msg_sent_count * 5) + 
            (msg_received_count * 3) + 
            (search_count * 2)
        )::DECIMAL as engagement_score;
END;
$$;

-- =====================================================
-- REAL-TIME ENHANCEMENTS
-- =====================================================

-- Enable realtime for messages
ALTER PUBLICATION supabase_realtime ADD TABLE messages;

-- Enable realtime for notifications  
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- Enable realtime for push_subscriptions
ALTER PUBLICATION supabase_realtime ADD TABLE push_subscriptions;

-- =====================================================
-- DATABASE MAINTENANCE
-- =====================================================

-- Create function to vacuum and analyze tables
CREATE OR REPLACE FUNCTION maintain_tables()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Analyze tables for query optimization
    ANALYZE profiles;
    ANALYZE messages;
    ANALYZE notifications;
    ANALYZE user_passions;
    ANALYZE profile_languages;
    ANALYZE analytics_events;
    
    -- Clean up old data
    DELETE FROM analytics_events WHERE created_at < NOW() - INTERVAL '90 days';
    DELETE FROM push_subscriptions WHERE last_used < NOW() - INTERVAL '30 days';
END;
$$;

-- =====================================================
-- AUDIT LOG TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    table_name TEXT,
    record_id TEXT,
    old_data JSONB,
    new_data JSONB,
    ip_address TEXT
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Only admins can read audit logs
CREATE POLICY "Allow admins to view audit logs" ON audit_logs
    FOR SELECT USING (auth.role() = 'authenticated');

-- Policy: System can insert audit logs
CREATE POLICY "Allow service role to insert audit logs" ON audit_logs
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_action ON audit_logs(user_id, action);

-- =====================================================
-- TRIGGER FOR AUDIT LOGGING
-- =====================================================
CREATE OR REPLACE FUNCTION audit_trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_logs (user_id, action, table_name, new_data)
        VALUES (auth.uid(), 'INSERT', TG_TABLE_NAME, to_jsonb(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_logs (user_id, action, table_name, old_data, new_data)
        VALUES (auth.uid(), 'UPDATE', TG_TABLE_NAME, to_jsonb(OLD), to_jsonb(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO audit_logs (user_id, action, table_name, old_data)
        VALUES (auth.uid(), 'DELETE', TG_TABLE_NAME, to_jsonb(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

-- Apply audit trigger to sensitive tables
DROP TRIGGER IF EXISTS profiles_audit ON profiles;
CREATE TRIGGER profiles_audit AFTER INSERT OR UPDATE OR DELETE ON profiles
FOR EACH ROW EXECUTE FUNCTION audit_trigger();

DROP TRIGGER IF EXISTS messages_audit ON messages;
CREATE TRIGGER messages_audit AFTER INSERT OR UPDATE OR DELETE ON messages
FOR EACH ROW EXECUTE FUNCTION audit_trigger();

DROP TRIGGER IF EXISTS blocked_users_audit ON blocked_users;
CREATE TRIGGER blocked_users_audit AFTER INSERT OR UPDATE OR DELETE ON blocked_users
FOR EACH ROW EXECUTE FUNCTION audit_trigger();

-- =====================================================
-- FINAL PERFORMANCE TUNING
-- =====================================================
-- Analyze all tables
ANALYZE;

-- Set statement timeout for long-running queries
ALTER DATABASE CURRENT SET statement_timeout = '30s';
