// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      boxShadow: {
        'glass-sm': '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        'glass-md': '0 10px 15px -3px rgb(0 0 0 / 0.05), 0 4px 6px -4px rgb(0 0 0 / 0.05)',
        'glass-lg': '0 20px 25px -5px rgb(0 0 0 / 0.05), 0 8px 10px -6px rgb(0 0 0 / 0.05)',
        'glass-glow': '0 0 20px 0 rgb(var(--color-brand-rgb) / 0.15)',
        'elevated': '0 10px 30px -5px rgb(0 0 0 / 0.1)',
      },
      backdropBlur: {
        'glass': '16px',
        'glass-heavy': '24px',
      },
      fontFamily: {
        sans: ['var(--font-outfit)', 'sans-serif'],
        heading: ['var(--font-space-grotesk)', 'sans-serif'],
      },
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        accent: 'var(--color-accent)',
        background: 'var(--color-background)',
        'background-secondary': 'var(--color-background-secondary)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        surface: 'rgb(var(--color-surface-rgb) / <alpha-value>)',
        'surface-secondary': 'rgb(var(--color-surface-secondary-rgb) / <alpha-value>)',
        'surface-overlay': 'rgb(var(--color-surface-overlay-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground-rgb) / <alpha-value>)',
        muted: 'rgb(var(--color-muted-rgb) / <alpha-value>)',
        faint: 'rgb(var(--color-faint-rgb) / <alpha-value>)',
        line: 'rgb(var(--color-line-rgb) / <alpha-value>)',
        brand: 'rgb(var(--color-brand-rgb) / <alpha-value>)',
        'brand-soft': 'rgb(var(--color-brand-soft-rgb) / <alpha-value>)',
        'brand-start': 'rgb(var(--color-brand-start-rgb) / <alpha-value>)',
        'brand-end': 'rgb(var(--color-brand-end-rgb) / <alpha-value>)',
        'brand-start-hover': 'rgb(var(--color-brand-start-hover-rgb) / <alpha-value>)',
        'brand-end-hover': 'rgb(var(--color-brand-end-hover-rgb) / <alpha-value>)',
        connection: 'rgb(var(--color-connection-rgb) / <alpha-value>)',
        'connection-soft': 'rgb(var(--color-connection-soft-rgb) / <alpha-value>)',
        'connection-start': 'rgb(var(--color-connection-start-rgb) / <alpha-value>)',
        'connection-end': 'rgb(var(--color-connection-end-rgb) / <alpha-value>)',
        'connection-start-hover': 'rgb(var(--color-connection-start-hover-rgb) / <alpha-value>)',
        'connection-end-hover': 'rgb(var(--color-connection-end-hover-rgb) / <alpha-value>)',
        discovery: 'rgb(var(--color-discovery-rgb) / <alpha-value>)',
        'discovery-soft': 'rgb(var(--color-discovery-soft-rgb) / <alpha-value>)',
        'discovery-start': 'rgb(var(--color-discovery-start-rgb) / <alpha-value>)',
        'discovery-end': 'rgb(var(--color-discovery-end-rgb) / <alpha-value>)',
        'discovery-start-hover': 'rgb(var(--color-discovery-start-hover-rgb) / <alpha-value>)',
        'discovery-end-hover': 'rgb(var(--color-discovery-end-hover-rgb) / <alpha-value>)',
        'success-soft': 'rgb(var(--color-success-soft-rgb) / <alpha-value>)',
        'success-start': 'rgb(var(--color-success-start-rgb) / <alpha-value>)',
        'success-end': 'rgb(var(--color-success-end-rgb) / <alpha-value>)',
        'success-start-hover': 'rgb(var(--color-success-start-hover-rgb) / <alpha-value>)',
        'success-end-hover': 'rgb(var(--color-success-end-hover-rgb) / <alpha-value>)',
        'warning-soft': 'rgb(var(--color-warning-soft-rgb) / <alpha-value>)',
        'warning-start': 'rgb(var(--color-warning-start-rgb) / <alpha-value>)',
        'warning-end': 'rgb(var(--color-warning-end-rgb) / <alpha-value>)',
        'warning-start-hover': 'rgb(var(--color-warning-start-hover-rgb) / <alpha-value>)',
        'warning-end-hover': 'rgb(var(--color-warning-end-hover-rgb) / <alpha-value>)',
        danger: 'rgb(var(--color-danger-rgb) / <alpha-value>)',
        'danger-soft': 'rgb(var(--color-danger-soft-rgb) / <alpha-value>)',
        'danger-start': 'rgb(var(--color-danger-start-rgb) / <alpha-value>)',
        'danger-end': 'rgb(var(--color-danger-end-rgb) / <alpha-value>)',
        'danger-start-hover': 'rgb(var(--color-danger-start-hover-rgb) / <alpha-value>)',
        'danger-end-hover': 'rgb(var(--color-danger-end-hover-rgb) / <alpha-value>)',
        info: 'rgb(var(--color-info-rgb) / <alpha-value>)',
        'info-soft': 'rgb(var(--color-info-soft-rgb) / <alpha-value>)',
        'info-start': 'rgb(var(--color-info-start-rgb) / <alpha-value>)',
        'info-end': 'rgb(var(--color-info-end-rgb) / <alpha-value>)',
        'info-start-hover': 'rgb(var(--color-info-start-hover-rgb) / <alpha-value>)',
        'info-end-hover': 'rgb(var(--color-info-end-hover-rgb) / <alpha-value>)',
        approval: 'rgb(var(--color-approval-rgb) / <alpha-value>)',
        'approval-soft': 'rgb(var(--color-approval-soft-rgb) / <alpha-value>)',
        'approval-start': 'rgb(var(--color-approval-start-rgb) / <alpha-value>)',
        'approval-end': 'rgb(var(--color-approval-end-rgb) / <alpha-value>)',
        'approval-start-hover': 'rgb(var(--color-approval-start-hover-rgb) / <alpha-value>)',
        'approval-end-hover': 'rgb(var(--color-approval-end-hover-rgb) / <alpha-value>)',
        focus: 'rgb(var(--color-focus-rgb) / <alpha-value>)',
        feature: {
          connection: 'rgb(var(--color-connection-rgb) / <alpha-value>)',
          discovery: 'rgb(var(--color-discovery-rgb) / <alpha-value>)',
        },
        status: {
          approval: 'rgb(var(--color-approval-rgb) / <alpha-value>)',
          danger: 'rgb(var(--color-danger-rgb) / <alpha-value>)',
          info: 'rgb(var(--color-info-rgb) / <alpha-value>)',
          success: 'rgb(var(--color-success-rgb) / <alpha-value>)',
          warning: 'rgb(var(--color-warning-rgb) / <alpha-value>)',
        },
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-pattern': "url('/grid.svg')", // Assuming you might add a pattern later
      }
    },
  },
  plugins: [],
};
