-- Production Setup SQL Script for Skillogue
-- This script should be applied to production database
-- Contains: Blocking Enhancement, Contact Us, Additional RLS Policies

-- =====================================================
-- CONTACT REQUESTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved'))
);

ALTER TABLE contact_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anyone to create contact requests" ON contact_requests;
DROP POLICY IF EXISTS "Allow users to view own contact requests" ON contact_requests;
DROP POLICY IF EXISTS "Allow admins to view all contact requests" ON contact_requests;

CREATE POLICY "Allow anyone to create contact requests" ON contact_requests
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow users to view own contact requests" ON contact_requests
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow admins to view all contact requests" ON contact_requests
    FOR SELECT USING (auth.role() = 'authenticated');

-- =====================================================
-- ENHANCED BLOCKING FUNCTIONALITY
-- =====================================================
-- Create a function to check mutual blocking
CREATE OR REPLACE FUNCTION check_mutual_block(user_a UUID, user_b UUID)
RETURNS TABLE(blocked_by_a BOOLEAN, blocked_by_b BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        EXISTS(SELECT 1 FROM blocked_users WHERE blocker_id = user_a AND blocked_id = user_b) as blocked_by_a,
        EXISTS(SELECT 1 FROM blocked_users WHERE blocker_id = user_b AND blocked_id = user_a) as blocked_by_b;
END;
$$;

-- =====================================================
-- ADDITIONAL RLS POLICIES
-- =====================================================

DROP POLICY IF EXISTS "Allow admins to view all reports" ON reports;
DROP POLICY IF EXISTS "Allow admins to update reports" ON reports;

CREATE POLICY "Allow admins to view all reports" ON reports
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow admins to update reports" ON reports
    FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow admins to view all verification requests" ON verification_requests;
DROP POLICY IF EXISTS "Allow admins to update verification requests" ON verification_requests;

CREATE POLICY "Allow admins to view all verification requests" ON verification_requests
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow admins to update verification requests" ON verification_requests
    FOR UPDATE USING (auth.role() = 'authenticated');

-- =====================================================
-- PERFORMANCE INDEXES
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_profiles_location ON profiles(location_id);
CREATE INDEX IF NOT EXISTS idx_profiles_age_gender ON profiles(age, gender);
CREATE INDEX IF NOT EXISTS idx_profiles_verified ON profiles(verified) WHERE verified = true;
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_verification_status ON verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_contact_status ON contact_requests(status);

-- =====================================================
-- SEED ADDITIONAL LOCATIONS
-- =====================================================
INSERT INTO locations (city, region, country) VALUES
    ('Miami', 'Florida', 'USA'),
    ('Seattle', 'Washington', 'USA'),
    ('Chicago', 'Illinois', 'USA'),
    ('Boston', 'Massachusetts', 'USA'),
    ('Austin', 'Texas', 'USA'),
    ('Denver', 'Colorado', 'USA'),
    ('San Francisco', 'California', 'USA'),
    ('Manchester', 'England', 'UK'),
    ('Edinburgh', 'Scotland', 'UK'),
    ('Birmingham', 'England', 'UK'),
    ('Munich', 'Bavaria', 'Germany'),
    ('Hamburg', 'Hamburg', 'Germany'),
    ('Madrid', 'Madrid', 'Spain'),
    ('Valencia', 'Valencia', 'Spain'),
    ('Milan', 'Lombardy', 'Italy'),
    ('Naples', 'Campania', 'Italy'),
    ('Sydney', 'New South Wales', 'Australia'),
    ('Melbourne', 'Victoria', 'Australia'),
    ('Brisbane', 'Queensland', 'Australia'),
    ('Vancouver', 'British Columbia', 'Canada'),
    ('Montreal', 'Quebec', 'Canada'),
    ('Calgary', 'Alberta', 'Canada'),
    ('Dubai', 'Dubai', 'UAE'),
    ('Abu Dhabi', 'Abu Dhabi', 'UAE'),
    ('Doha', 'Doha', 'Qatar')
ON CONFLICT DO NOTHING;
