-- Create tables for Skillogue application

-- Locations table
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city TEXT,
    region TEXT,
    country TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Profiles table (extends Supabase auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    first_name TEXT,
    last_name TEXT,
    about_me TEXT,
    age INTEGER,
    gender TEXT,
    verified BOOLEAN DEFAULT FALSE,
    is_private BOOLEAN DEFAULT FALSE,
    show_age BOOLEAN DEFAULT TRUE,
    show_location BOOLEAN DEFAULT TRUE,
    location_id BIGINT REFERENCES locations(id),
    avatar_url TEXT
);

-- Passions table
CREATE TABLE IF NOT EXISTS passions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Languages table
CREATE TABLE IF NOT EXISTS languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Passions (junction table)
CREATE TABLE IF NOT EXISTS user_passions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    passion_id BIGINT REFERENCES passions(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, passion_id)
);

-- Profile Languages (junction table)
CREATE TABLE IF NOT EXISTS profile_languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    language_id BIGINT REFERENCES languages(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(profile_id, language_id)
);

-- Messages table
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL
);

-- Notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE
);

-- Favorites table
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    favorite_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    UNIQUE(user_id, favorite_id)
);

-- Saved Searches table
CREATE TABLE IF NOT EXISTS saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    query TEXT,
    location TEXT,
    min_age INTEGER,
    max_age INTEGER,
    language TEXT,
    gender TEXT,
    passion_ids BIGINT[]
);

-- Reports table
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    reporter_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    reported_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending'
);

-- Verification Requests table
CREATE TABLE IF NOT EXISTS verification_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE passions ENABLE ROW LEVEL SECURITY;
ALTER TABLE languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_passions ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_searches ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_requests ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Allow public read access to passions" ON passions;
DROP POLICY IF EXISTS "Allow public read access to languages" ON languages;
DROP POLICY IF EXISTS "Allow public read access to locations" ON locations;
DROP POLICY IF EXISTS "Allow public read access to profiles" ON profiles;
DROP POLICY IF EXISTS "Allow users to update own profile" ON profiles;
DROP POLICY IF EXISTS "Allow public read access to user_passions" ON user_passions;
DROP POLICY IF EXISTS "Allow users to manage own passions" ON user_passions;
DROP POLICY IF EXISTS "Allow public read access to profile_languages" ON profile_languages;
DROP POLICY IF EXISTS "Allow users to manage own languages" ON profile_languages;
DROP POLICY IF EXISTS "Allow users to read own messages" ON messages;
DROP POLICY IF EXISTS "Allow users to send messages" ON messages;
DROP POLICY IF EXISTS "Allow users to read own notifications" ON notifications;
DROP POLICY IF EXISTS "Allow users to update own notifications" ON notifications;
DROP POLICY IF EXISTS "Allow users to read own favorites" ON favorites;
DROP POLICY IF EXISTS "Allow users to manage own favorites" ON favorites;
DROP POLICY IF EXISTS "Allow users to manage own saved searches" ON saved_searches;
DROP POLICY IF EXISTS "Allow users to create reports" ON reports;
DROP POLICY IF EXISTS "Allow users to create verification requests" ON verification_requests;
DROP POLICY IF EXISTS "Allow users to read own verification requests" ON verification_requests;

-- Create policies for public read access to passions and languages
CREATE POLICY "Allow public read access to passions" ON passions
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access to languages" ON languages
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access to locations" ON locations
    FOR SELECT USING (true);

-- Create policies for profiles
CREATE POLICY "Allow public read access to profiles" ON profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update own profile" ON profiles
    FOR UPDATE USING (auth.uid() = id);

-- Create policies for user_passions
CREATE POLICY "Allow public read access to user_passions" ON user_passions
    FOR SELECT USING (true);

CREATE POLICY "Allow users to manage own passions" ON user_passions
    FOR ALL USING (auth.uid() = user_id);

-- Create policies for profile_languages
CREATE POLICY "Allow public read access to profile_languages" ON profile_languages
    FOR SELECT USING (true);

CREATE POLICY "Allow users to manage own languages" ON profile_languages
    FOR ALL USING (auth.uid() = profile_id);

-- Create policies for messages
CREATE POLICY "Allow users to read own messages" ON messages
    FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Allow users to send messages" ON messages
    FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Create policies for notifications
CREATE POLICY "Allow users to read own notifications" ON notifications
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to update own notifications" ON notifications
    FOR UPDATE USING (auth.uid() = user_id);

-- Create policies for favorites
CREATE POLICY "Allow users to read own favorites" ON favorites
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to manage own favorites" ON favorites
    FOR ALL USING (auth.uid() = user_id);

-- Create policies for saved_searches
CREATE POLICY "Allow users to manage own saved searches" ON saved_searches
    FOR ALL USING (auth.uid() = user_id);

-- Create policies for reports
CREATE POLICY "Allow users to create reports" ON reports
    FOR INSERT WITH CHECK (auth.uid() = reporter_id);

-- Create policies for verification_requests
CREATE POLICY "Allow users to create verification requests" ON verification_requests
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to read own verification requests" ON verification_requests
    FOR SELECT USING (auth.uid() = user_id);
