/*
  Skillogue Database Schema
  -------------------------
  This schema defines the structure for the Skillogue application.
  It is organized into logical sections:
  1. Reference Data
  2. Core Profiles
  3. Profile Associations
  4. Social & Interactions
  5. User Settings
*/

-- ==========================================
-- 1. Reference Data (Lookups)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.languages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.passions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.locations (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  city text,
  region text,
  country text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ==========================================
-- 2. Core User Profiles
-- ==========================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL PRIMARY KEY,
  
  -- Basic Info
  first_name text,
  last_name text,
  about_me text,
  gender text,
  age integer,
  location_id bigint REFERENCES public.locations(id),
  
  -- Status & Role
  verified boolean NOT NULL DEFAULT false,
  role text DEFAULT 'user'::text,
  
  -- Privacy Settings
  is_private boolean DEFAULT false,
  show_age boolean DEFAULT true,
  show_location boolean DEFAULT true,
  
  -- Metadata
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  -- Foreign Key to Auth
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- ==========================================
-- 3. Profile Associations
-- ==========================================

CREATE TABLE IF NOT EXISTS public.profile_languages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.profiles(id),
  language_id bigint NOT NULL REFERENCES public.languages(id)
);

CREATE TABLE IF NOT EXISTS public.profile_passions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.profiles(id),
  passion_id bigint NOT NULL REFERENCES public.passions(id)
);

-- ==========================================
-- 4. Social & Interactions
-- ==========================================

CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES public.profiles(id),
  receiver_id uuid NOT NULL REFERENCES public.profiles(id),
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  actor_id uuid NOT NULL REFERENCES public.profiles(id),
  type text NOT NULL,
  target_id text,
  read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blocks (
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  blocked_user_id uuid NOT NULL REFERENCES public.profiles(id),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT blocks_pkey PRIMARY KEY (user_id, blocked_user_id)
);

CREATE TABLE IF NOT EXISTS public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid NOT NULL REFERENCES public.profiles(id),
  reported_user_id uuid NOT NULL REFERENCES public.profiles(id),
  reason text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ==========================================
-- 5. User Settings & Data
-- ==========================================

CREATE TABLE IF NOT EXISTS public.saved_searches (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  name text NOT NULL,
  
  -- Search Criteria
  query text,
  location text,
  min_age integer,
  max_age integer,
  language text,
  gender text,
  passion_ids bigint[],
  
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ==========================================
-- 6. Migrations / Fixes
-- ==========================================

-- Ensure privacy columns exist (Idempotent check for existing databases)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'is_private') THEN
        ALTER TABLE public.profiles ADD COLUMN is_private boolean DEFAULT false;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'show_age') THEN
        ALTER TABLE public.profiles ADD COLUMN show_age boolean DEFAULT true;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'show_location') THEN
        ALTER TABLE public.profiles ADD COLUMN show_location boolean DEFAULT true;
    END IF;
END $$;
